version: '3.3'

services:

  db:
    image: mysql:8
    container_name: myfit_mysql_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
      MYSQL_USER: myfituser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - backend

  app:
    image: myfit
    container_name: myfit_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/example?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: myfituser
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: