spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/example
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 862710517006-kh5gp11qs0h3u71pqpf0sob693qen18k.apps.googleusercontent.com
            client-secret: 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
server:
  error:
    whitelabel:
      enabled: false